# Generated by Django 2.0.1 on 2018-01-29 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0003_auto_20180124_2015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='name',
            new_name='player_name',
        ),
    ]
