# Generated by Django 2.0.1 on 2018-01-29 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0004_auto_20180129_1021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='player_name',
            new_name='name',
        ),
    ]
