# Generated by Django 2.0.1 on 2018-01-29 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0005_auto_20180129_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='score_admin',
            field=models.CharField(default='auth.user', max_length=100),
        ),
    ]
