# Generated by Django 2.0.1 on 2018-01-29 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0006_score_score_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='score_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
