# Generated by Django 2.0.1 on 2018-02-01 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0007_auto_20180129_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='score_admin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
